// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RebecaBarrezueta_Examen1P.Data;

#nullable disable

namespace RebecaBarrezueta_Examen1P.Migrations
{
    [DbContext(typeof(RebecaBarrezueta_Examen1PContext))]
    [Migration("20240424170309_Cambios22")]
    partial class Cambios22
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RebecaBarrezueta_Examen1P.Models.PromocionRB", b =>
                {
                    b.Property<int>("PromocionID_RB")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PromocionID_RB"));

                    b.Property<string>("Descripcion_RB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaPromo_RB")
                        .HasColumnType("datetime2");

                    b.Property<int>("ZapatosID_RB")
                        .HasColumnType("int");

                    b.Property<int?>("ZapatosRBZapatosID_RB")
                        .HasColumnType("int");

                    b.HasKey("PromocionID_RB");

                    b.HasIndex("ZapatosRBZapatosID_RB");

                    b.ToTable("PromocionRB");
                });

            modelBuilder.Entity("RebecaBarrezueta_Examen1P.Models.ZapatosRB", b =>
                {
                    b.Property<int>("ZapatosID_RB")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZapatosID_RB"));

                    b.Property<bool>("EdicionEspecial_RB")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre_RB")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Precio_RB")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ZapatosID_RB");

                    b.ToTable("ZapatosRB");
                });

            modelBuilder.Entity("RebecaBarrezueta_Examen1P.Models.PromocionRB", b =>
                {
                    b.HasOne("RebecaBarrezueta_Examen1P.Models.ZapatosRB", "ZapatosRB")
                        .WithMany("PromocionRB")
                        .HasForeignKey("ZapatosRBZapatosID_RB");

                    b.Navigation("ZapatosRB");
                });

            modelBuilder.Entity("RebecaBarrezueta_Examen1P.Models.ZapatosRB", b =>
                {
                    b.Navigation("PromocionRB");
                });
#pragma warning restore 612, 618
        }
    }
}
